-- Module:Data/BlastFurnaceModes
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 2 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_bfm_te"] = {
    identifier = "_base_bfm_te",
    name = "Technum",
    icon = "molten_te",
    inputs = {
      {
        identifier = "_base_ore_technum",
        amount = 640,
        percentage = 1,
      },
      {
        identifier = "_base_coked_ignium",
        amount = 320,
        percentage = 1,
      },
      {
        identifier = "_base_ore_mineral_rock",
        amount = 128,
        percentage = 1,
      },
    },
    elemental_outputs = {
      {
        identifier = "_base_molten_te",
        amount = 5760,
      },
      {
        identifier = "_base_bf_slag",
        amount = 640,
      },
    },
    waste_gas = {
      identifier = "_base_waste_gas",
      amount = 12,
    },
  },
  ["_base_bfm_xf"] = {
    identifier = "_base_bfm_xf",
    name = "Xenoferrite",
    icon = "molten_xf",
    inputs = {
      {
        identifier = "_base_ore_xenoferrite",
        amount = 640,
        percentage = 1,
      },
      {
        identifier = "_base_coked_ignium",
        amount = 320,
        percentage = 1,
      },
      {
        identifier = "_base_ore_mineral_rock",
        amount = 128,
        percentage = 1,
      },
    },
    elemental_outputs = {
      {
        identifier = "_base_molten_xf",
        amount = 5760,
      },
      {
        identifier = "_base_bf_slag",
        amount = 640,
      },
    },
    waste_gas = {
      identifier = "_base_waste_gas",
      amount = 12,
    },
  },
}
