-- Module:Data/CompanyRanks
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 20 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_0"] = {
    identifier = "_base_0",
    name = "",
  },
  ["_base_1"] = {
    identifier = "_base_1",
    name = "",
  },
  ["_base_10"] = {
    identifier = "_base_10",
    name = "",
  },
  ["_base_11"] = {
    identifier = "_base_11",
    name = "",
  },
  ["_base_12"] = {
    identifier = "_base_12",
    name = "",
  },
  ["_base_13"] = {
    identifier = "_base_13",
    name = "",
  },
  ["_base_14"] = {
    identifier = "_base_14",
    name = "",
  },
  ["_base_15"] = {
    identifier = "_base_15",
    name = "",
  },
  ["_base_16"] = {
    identifier = "_base_16",
    name = "",
  },
  ["_base_17"] = {
    identifier = "_base_17",
    name = "",
  },
  ["_base_18"] = {
    identifier = "_base_18",
    name = "",
  },
  ["_base_19"] = {
    identifier = "_base_19",
    name = "",
  },
  ["_base_2"] = {
    identifier = "_base_2",
    name = "",
  },
  ["_base_3"] = {
    identifier = "_base_3",
    name = "",
  },
  ["_base_4"] = {
    identifier = "_base_4",
    name = "",
  },
  ["_base_5"] = {
    identifier = "_base_5",
    name = "",
  },
  ["_base_6"] = {
    identifier = "_base_6",
    name = "",
  },
  ["_base_7"] = {
    identifier = "_base_7",
    name = "",
  },
  ["_base_8"] = {
    identifier = "_base_8",
    name = "",
  },
  ["_base_9"] = {
    identifier = "_base_9",
    name = "",
  },
}
