-- Module:Data/ConversionGroups
-- Auto-generated by foundry_parser on 2026-05-31 10:26 UTC
-- 9 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_assembler"] = {
    identifier = "_base_assembler",
  },
  ["_base_conveyorBalancer"] = {
    identifier = "_base_conveyorBalancer",
  },
  ["_base_conveyor_belts"] = {
    identifier = "_base_conveyor_belts",
  },
  ["_base_crusher"] = {
    identifier = "_base_crusher",
  },
  ["_base_droneMiner"] = {
    identifier = "_base_droneMiner",
  },
  ["_base_escalators"] = {
    identifier = "_base_escalators",
  },
  ["_base_freightElevator"] = {
    identifier = "_base_freightElevator",
  },
  ["_base_lava_smelter"] = {
    identifier = "_base_lava_smelter",
  },
  ["_base_train_signal"] = {
    identifier = "_base_train_signal",
  },
}
