-- Module:Data/CraftingTags
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 17 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["advanced_smelter"] = {
    identifier = "advanced_smelter",
    name = "Advanced Smelter",
  },
  ["assembler"] = {
    identifier = "assembler",
    name = "Assembler",
  },
  ["assembler_fluid"] = {
    identifier = "assembler_fluid",
    name = "Fluid-Assembler",
  },
  ["barrel_filler"] = {
    identifier = "barrel_filler",
    name = "Barrel Filler",
  },
  ["casting_machine"] = {
    identifier = "casting_machine",
    name = "Casting Machine",
  },
  ["character"] = {
    identifier = "character",
    name = "Character",
  },
  ["chemical_processor"] = {
    identifier = "chemical_processor",
    name = "Chemical Processor",
  },
  ["crusher"] = {
    identifier = "crusher",
    name = "Crusher",
  },
  ["crystal_refiner"] = {
    identifier = "crystal_refiner",
    name = "Crystal Refiner",
  },
  ["distillation_column"] = {
    identifier = "distillation_column",
    name = "Distillation Column",
  },
  ["electric_arc_furnace"] = {
    identifier = "electric_arc_furnace",
    name = "Electric Arc Furnace",
  },
  ["geothermal_generator"] = {
    identifier = "geothermal_generator",
    name = "Geothermal Generator",
  },
  ["greenhouse"] = {
    identifier = "greenhouse",
    name = "Greenhouse",
  },
  ["heavy_caster"] = {
    identifier = "heavy_caster",
    name = "Heavy Caster",
  },
  ["npp_fuel_mixer"] = {
    identifier = "npp_fuel_mixer",
    name = "Fuel Mixer",
  },
  ["smelter"] = {
    identifier = "smelter",
    name = "Smelter",
  },
  ["smelter_lava"] = {
    identifier = "smelter_lava",
    name = "Lava-Smelter",
  },
}
