-- Module:Data/ExplorationUnlocks
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 55 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_building_drone_range_i"] = {
    identifier = "_base_building_drone_range_i",
    title = "Construction Drone Range I",
    description = "Increases the range of the construction drone by 20 voxels.",
    category_id = "_base_building_drone",
    icon = "construction_drone_range",
    unlock_flags = "DroneRangeIncrease",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 10,
      },
    },
    research_dependencies = { "_base_character_improvement_i" },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_building_drone_range_ii"] = {
    identifier = "_base_building_drone_range_ii",
    title = "Construction Drone Range II",
    description = "Increases the range of the construction drone by 20 voxels.",
    category_id = "_base_building_drone",
    icon = "construction_drone_range",
    unlock_flags = "DroneRangeIncrease",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 20,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_building_drone_range_i",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_building_drone_range_iii"] = {
    identifier = "_base_building_drone_range_iii",
    title = "Construction Drone Range III",
    description = "Increases the range of the construction drone by 20 voxels.",
    category_id = "_base_building_drone",
    icon = "construction_drone_range",
    unlock_flags = "DroneRangeIncrease",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 1,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 25,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_building_drone_range_ii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_building_drone_range_iv"] = {
    identifier = "_base_building_drone_range_iv",
    title = "Construction Drone Range IV",
    description = "Increases the range of the construction drone by 20 voxels.",
    category_id = "_base_building_drone",
    icon = "construction_drone_range",
    unlock_flags = "DroneRangeIncrease",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 50,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_building_drone_range_iii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_building_drone_range_v"] = {
    identifier = "_base_building_drone_range_v",
    title = "Construction Drone Range V",
    description = "Increases the range of the construction drone by 20 voxels.",
    category_id = "_base_building_drone",
    icon = "construction_drone_range",
    unlock_flags = "DroneRangeIncrease",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 10,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_building_drone_range_iv",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_crafting_speed_i"] = {
    identifier = "_base_character_crafting_speed_i",
    title = "Character Crafting Speed I",
    description = "Decreases character crafting time by 10%.",
    category_id = "_base_character_crafting_speed",
    icon = "character_crafting_speed_i",
    unlock_flags = "CharacterCraftingSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 20,
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_crafting_speed_ii"] = {
    identifier = "_base_character_crafting_speed_ii",
    title = "Character Crafting Speed II",
    description = "Decreases character crafting time by 10%.",
    category_id = "_base_character_crafting_speed",
    icon = "character_crafting_speed_ii",
    unlock_flags = "CharacterCraftingSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 20,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_crafting_speed_i",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_crafting_speed_iii"] = {
    identifier = "_base_character_crafting_speed_iii",
    title = "Character Crafting Speed III",
    description = "Decreases character crafting time by 10%.",
    category_id = "_base_character_crafting_speed",
    icon = "character_crafting_speed_iii",
    unlock_flags = "CharacterCraftingSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 1,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_crafting_speed_ii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_crafting_speed_iv"] = {
    identifier = "_base_character_crafting_speed_iv",
    title = "Character Crafting Speed IV",
    description = "Decreases character crafting time by 10%.",
    category_id = "_base_character_crafting_speed",
    icon = "character_crafting_speed_iv",
    unlock_flags = "CharacterCraftingSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 50,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_crafting_speed_iii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_crafting_speed_v"] = {
    identifier = "_base_character_crafting_speed_v",
    title = "Character Crafting Speed V",
    description = "Decreases character crafting time by 10%.",
    category_id = "_base_character_crafting_speed",
    icon = "character_crafting_speed_v",
    unlock_flags = "CharacterCraftingSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 10,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_crafting_speed_iv",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_slots_i"] = {
    identifier = "_base_character_logistics_slots_i",
    title = "Resupply Slots I",
    description = "Unlocks more resupply slots for the character.",
    category_id = "_base_personal_logistics",
    icon = "logistics_slots_i",
    unlock_flags = "PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    sort_order = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 25,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_unlock",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_slots_ii"] = {
    identifier = "_base_character_logistics_slots_ii",
    title = "Resupply Slots II",
    description = "Unlocks more resupply slots for the character.",
    category_id = "_base_personal_logistics",
    icon = "logistics_slots_ii",
    unlock_flags = "PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 40,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_slots_i",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_slots_iii"] = {
    identifier = "_base_character_logistics_slots_iii",
    title = "Resupply Slots III",
    description = "Unlocks more resupply slots for the character.",
    category_id = "_base_personal_logistics",
    icon = "logistics_slots_iii",
    unlock_flags = "PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    sort_order = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 40,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_slots_ii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_slots_iv"] = {
    identifier = "_base_character_logistics_slots_iv",
    title = "Resupply Slots IV",
    description = "Unlocks more resupply slots for the character.",
    category_id = "_base_personal_logistics",
    icon = "logistics_slots_iv",
    unlock_flags = "PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 200,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_slots_iii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_slots_v"] = {
    identifier = "_base_character_logistics_slots_v",
    title = "Resupply Slots V",
    description = "Unlocks more resupply slots for the character.",
    category_id = "_base_personal_logistics",
    icon = "logistics_slots_v",
    unlock_flags = "PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 20,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_slots_iv",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_throughput_i"] = {
    identifier = "_base_character_logistics_throughput_i",
    title = "Throughput Increase I",
    description = "Increases the speed of resupply.",
    category_id = "_base_personal_logistics",
    icon = "logistics_speed_i",
    unlock_flags = "PersonalLogisticsTicksPerUpdateChange",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 25,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_unlock",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_throughput_ii"] = {
    identifier = "_base_character_logistics_throughput_ii",
    title = "Throughput Increase II",
    description = "Increases the speed of resupply.",
    category_id = "_base_personal_logistics",
    icon = "logistics_speed_ii",
    unlock_flags = "PersonalLogisticsTicksPerUpdateChange",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 40,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_throughput_i",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_throughput_iii"] = {
    identifier = "_base_character_logistics_throughput_iii",
    title = "Throughput Increase III",
    description = "Increases the speed of resupply.",
    category_id = "_base_personal_logistics",
    icon = "logistics_speed_iii",
    unlock_flags = "PersonalLogisticsTicksPerUpdateChange",
    seconds_to_unlock = 5,
    sort_order = 15,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 40,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_throughput_ii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_throughput_iv"] = {
    identifier = "_base_character_logistics_throughput_iv",
    title = "Throughput Increase IV",
    description = "Increases the speed of resupply.",
    category_id = "_base_personal_logistics",
    icon = "logistics_speed_iv",
    unlock_flags = "PersonalLogisticsTicksPerUpdateChange",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 200,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_throughput_iii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_throughput_v"] = {
    identifier = "_base_character_logistics_throughput_v",
    title = "Throughput Increase V",
    description = "Increases the speed of resupply.",
    category_id = "_base_personal_logistics",
    icon = "logistics_speed_v",
    unlock_flags = "PersonalLogisticsTicksPerUpdateChange",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 20,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_character_logistics_throughput_iv",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_character_logistics_unlock"] = {
    identifier = "_base_character_logistics_unlock",
    title = "Xeno-Logistics System",
    description = [[The alien scrap provides insight on how to teleport items over short distances. Analysis will allow us to gain sufficient insight to make use of a technology we call Xeno-Logistics.

The system allows us to automatically resupply items from Xeno-Logistics Containers into the character inventory through Xeno-Logistics Towers.

This cannot be used to move items between machines and is no substitution for various factory logistics.]],
    category_id = "_base_personal_logistics",
    icon = "xeno_logistic_container_i",
    unlock_flags = "UnlockCraftingRecipe|UnlocksPersonalLogistics|PersonalLogisticsSlots",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 25,
      },
    },
    crafting_recipe_unlocks = { "_base_logistics_tower_i", "_base_personal_logistic_container" },
  },
  ["_base_charged_crystal_production"] = {
    identifier = "_base_charged_crystal_production",
    title = "Charged Xeno-Crystal Production",
    description = "Unlocks the Crystal Refiner which allows to energize Xeno-Crystals into Charged Xeno-Crystals, which brings us one step closer to unlocking their true potential.",
    category_id = "_base_tools",
    icon = "crystal_refiner_i",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 10,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 100,
      },
    },
    research_dependencies = { "_base_energy_cell", "_base_geothermal_power" },
    crafting_recipe_unlocks = { "_base_crystal_refiner_i", "_base_crystal_ii" },
  },
  ["_base_crystal_mining"] = {
    identifier = "_base_crystal_mining",
    title = "Xeno-Crystal Mining",
    description = [[We have found super-condensed veins of Xeno-Crystals inside the lava caves. Similar to the Scrap-Mining we could utilize a specialized mining building to mine Xeno-Crystals from a seemingly endless source.

This also unlocks tracking of such deposits with the Short Range Scanner.]],
    category_id = "_base_tools",
    icon = "endless_miner_crystal_i",
    unlock_flags = "UnlockCraftingRecipe|ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 25,
      },
    },
    research_dependencies = { "_base_circuit_board", "_base_mining_force_i" },
    crafting_recipe_unlocks = { "_base_endless_miner_crystals_i" },
  },
  ["_base_crystal_ore_refinement"] = {
    identifier = "_base_crystal_ore_refinement",
    title = "Crystal Ore Refinment",
    description = "In case we have excess crystals we could blend them with the ore rubble to reduce our ore consumption.",
    category_id = "_base_tools",
    icon = "crystal_ore_refinement",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 20,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 250,
      },
    },
    research_dependencies = { "_base_ore_refinement_i" },
    crafting_recipe_unlocks = { "_base_ore_xenoferrite_crystals", "_base_ore_technum_crystals" },
  },
  ["_base_double_jump"] = {
    identifier = "_base_double_jump",
    title = "Rocket Boots",
    description = "Upgrades the player character with rocket boots which allow double jumping by jumping again mid-air.",
    category_id = "_base_tools",
    icon = "rocket_jump",
    unlock_flags = "UnlocksDoubleJump",
    seconds_to_unlock = 5,
    sort_order = 50,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 10,
      },
    },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_drill_shape_2x2"] = {
    identifier = "_base_drill_shape_2x2",
    title = "Drill Shape: 2x2",
    description = "Allows to dig multiple blocks at once with the mining drill. Hold right mouse button (default key) to switch the drill shape.",
    category_id = "_base_drill_shapes",
    icon = "mining_2x2_rt",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 10,
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_drill_shape_3x3"] = {
    identifier = "_base_drill_shape_3x3",
    title = "Drill Shape: 3x3",
    description = "Allows to dig multiple blocks at once with the mining drill. Hold right mouse button (default key) to switch the drill shape.",
    category_id = "_base_drill_shapes",
    icon = "mining_3x3_rt",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 10,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_drill_shape_2x2",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_drill_shape_4x4"] = {
    identifier = "_base_drill_shape_4x4",
    title = "Drill Shape: 4x4",
    description = "Allows to dig multiple blocks at once with the mining laser. Hold right mouse button (default key) to switch the shape.",
    category_id = "_base_drill_shapes",
    icon = "mining_4x4_rt",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 50,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_drill_shape_3x3",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_drill_shape_5x5"] = {
    identifier = "_base_drill_shape_5x5",
    title = "Drill Shape: 5x5",
    description = "Allows to dig multiple blocks at once with the mining laser. Hold right mouse button (default key) to switch the shape.",
    category_id = "_base_drill_shapes",
    icon = "mining_5x5_rt",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 10,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_drill_shape_4x4",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_drill_ship_i"] = {
    identifier = "_base_drill_ship_i",
    title = "Drill Ship",
    description = "Unlocks the Drill Ship, which is a tunnel boring vehicle. It excels at digging tunnels, but can be useful for various excavation projects.",
    category_id = "_base_tools",
    icon = "drill_ship",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 5,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 50,
      },
    },
    research_dependencies = { "_base_hover_engine", "_base_circuit_board" },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_mining_drill_speed_i"] = {
    identifier = "_base_mining_drill_speed_i",
    title = "Mining Drill Speed I",
    description = "Decreases mining time by 20%.",
    category_id = "_base_dig_speed",
    icon = "hand_drill",
    unlock_flags = "MiningDrillSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 15,
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_mining_drill_speed_ii"] = {
    identifier = "_base_mining_drill_speed_ii",
    title = "Mining Drill Speed II",
    description = "Decreases mining time by 20%.",
    category_id = "_base_dig_speed",
    icon = "hand_drill",
    unlock_flags = "MiningDrillSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 15,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_mining_drill_speed_i",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_mining_drill_speed_iii"] = {
    identifier = "_base_mining_drill_speed_iii",
    title = "Mining Drill Speed III",
    description = "Decreases mining time by 20%.",
    category_id = "_base_dig_speed",
    icon = "hand_drill",
    unlock_flags = "MiningDrillSpeed",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 1,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 25,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_mining_drill_speed_ii",
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_mining_laser"] = {
    identifier = "_base_mining_laser",
    title = "Mining Laser",
    description = "A powerful mining laser that allows mining from a distance.",
    category_id = "_base_tools",
    icon = "mining_laser",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 50,
      },
    },
    research_dependencies = { "_base_energy_cell" },
    crafting_recipe_unlocks = { "_base_mining_laser" },
  },
  ["_base_personal_mining_drone_count_i"] = {
    identifier = "_base_personal_mining_drone_count_i",
    title = "Excavation Drone Count I",
    description = "Unlocks two additional personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_extra_rt_i",
    unlock_flags = "PersonalMiningDroneCount",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drones",
      },
    },
  },
  ["_base_personal_mining_drone_count_ii"] = {
    identifier = "_base_personal_mining_drone_count_ii",
    title = "Excavation Drone Count II",
    description = "Unlocks two additional personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_extra_rt_ii",
    unlock_flags = "PersonalMiningDroneCount",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_count_i",
      },
    },
  },
  ["_base_personal_mining_drone_count_iii"] = {
    identifier = "_base_personal_mining_drone_count_iii",
    title = "Excavation Drone Count III",
    description = "Unlocks two additional personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_extra_rt_iii",
    unlock_flags = "PersonalMiningDroneCount",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_count_ii",
      },
    },
  },
  ["_base_personal_mining_drone_count_iv"] = {
    identifier = "_base_personal_mining_drone_count_iv",
    title = "Excavation Drone Count IV",
    description = "Unlocks two additional personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_extra_rt_iv",
    unlock_flags = "PersonalMiningDroneCount",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 100,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_count_iii",
      },
    },
  },
  ["_base_personal_mining_drone_count_v"] = {
    identifier = "_base_personal_mining_drone_count_v",
    title = "Excavation Drone Count V",
    description = "Unlocks two additional personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_extra_rt_v",
    unlock_flags = "PersonalMiningDroneCount",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 26,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_count_iv",
      },
    },
  },
  ["_base_personal_mining_drone_speed_i"] = {
    identifier = "_base_personal_mining_drone_speed_i",
    title = "Excavation Drone Speed I",
    description = "Increases the movement speed of the personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "personal_mining_drone_speed_i",
    unlock_flags = "PersonalMiningDroneSpeed",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drones",
      },
    },
  },
  ["_base_personal_mining_drone_speed_ii"] = {
    identifier = "_base_personal_mining_drone_speed_ii",
    title = "Excavation Drone Speed II",
    description = "Increases the movement speed of the personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "personal_mining_drone_speed_ii",
    unlock_flags = "PersonalMiningDroneSpeed",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_speed_i",
      },
    },
  },
  ["_base_personal_mining_drone_speed_iii"] = {
    identifier = "_base_personal_mining_drone_speed_iii",
    title = "Excavation Drone Speed III",
    description = "Increases the movement speed of the personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "personal_mining_drone_speed_iii",
    unlock_flags = "PersonalMiningDroneSpeed",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 2,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 30,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_speed_ii",
      },
    },
  },
  ["_base_personal_mining_drone_speed_iv"] = {
    identifier = "_base_personal_mining_drone_speed_iv",
    title = "Excavation Drone Speed IV",
    description = "Increases the movement speed of the personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "personal_mining_drone_speed_iv",
    unlock_flags = "PersonalMiningDroneSpeed",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 100,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_speed_iii",
      },
    },
  },
  ["_base_personal_mining_drone_speed_v"] = {
    identifier = "_base_personal_mining_drone_speed_v",
    title = "Excavation Drone Speed V",
    description = "Increases the movement speed of the personal excavation drones. Use the Excavation Drone Controller handheld to command them.",
    category_id = "_base_personal_mining_drones",
    icon = "personal_mining_drone_speed_v",
    unlock_flags = "PersonalMiningDroneSpeed",
    seconds_to_unlock = 5,
    sort_order = 10,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 26,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_personal_mining_drone_speed_iv",
      },
    },
  },
  ["_base_personal_mining_drones"] = {
    identifier = "_base_personal_mining_drones",
    title = "Personal Excavation Drones",
    description = [[Unlocks personal excavation drones and their handheld controller. This tool allows you to designate mining areas. Once marked, those areas will be dug up by your personal excavation drones as long as you're close enough.]],
    category_id = "_base_personal_mining_drones",
    icon = "mining_controller_rt",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 25,
      },
    },
    crafting_recipe_unlocks = { "_base_drone_controller" },
  },
  ["_base_power_core_crafting"] = {
    identifier = "_base_power_core_crafting",
    title = "Xeno Power Core Manufacturing",
    description = "With the all the previous information we have previously gathered, we should now be able to make our own Xeno Power Cores.",
    category_id = "_base_tools",
    icon = "power_core_ii",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_ii",
        amount = 5,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_charged_crystal_production",
      },
    },
    research_dependencies = { "_base_super_alloy_production", "_base_rubber_production" },
    crafting_recipe_unlocks = { "_base_power_core_ii" },
  },
  ["_base_quarry_building_i"] = {
    identifier = "_base_quarry_building_i",
    title = "Quarry",
    description = "Unlocks the Quarry, a building which is able to excavate areas. It excels at digging shafts or pits, but can be useful for various excavation projects.",
    category_id = "_base_tools",
    icon = "quarry_building_i",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 75,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 25,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 50,
      },
    },
    research_dependencies = { "_base_mining_force_i" },
    crafting_recipe_unlocks = { "_base_quarry_building_i" },
  },
  ["_base_scrap_mining"] = {
    identifier = "_base_scrap_mining",
    title = "Xeno-Scrap Mining",
    description = [[We have found super-condensed masses of Xeno-Scrap underground and we can utilize a specialized mining building to mine Xeno-Scrap from a seemingly endless source.

This also unlocks tracking of such deposits with the Short Range Scanner.]],
    category_id = "_base_tools",
    icon = "endless_miner_scrap_i",
    unlock_flags = "UnlockCraftingRecipe|ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 10,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 100,
      },
    },
    research_dependencies = { "_base_circuit_board", "_base_mining_force_i" },
    crafting_recipe_unlocks = { "_base_endless_miner_scrap_i" },
  },
  ["_base_scrap_recycling"] = {
    identifier = "_base_scrap_recycling",
    title = "Scrap Recycling",
    description = "Unlocks the Scrap Recycler which allows to recycle Xeno-Scrap into components we can repurpose for other needs.",
    category_id = "_base_tools",
    icon = "recycler_scrap",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    sort_order = 20,
    requirements = {
      {
        itemTemplateIdentifier = "_base_power_core_i",
        amount = 5,
      },
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 50,
      },
    },
    research_dependencies = { "_base_basic_steelmaking" },
    crafting_recipe_unlocks = { "_base_recycler_scrap" },
  },
  ["_base_short_range_scanner"] = {
    identifier = "_base_short_range_scanner",
    title = "Short Range Scanner",
    description = [[Unlocks the Short Range Scanner, which allows us to track and locate Xeno-Scrap-Remnants on the surface.

Once unlocked, the scanner will appear at the top left of the screen.]],
    category_id = "_base_tools",
    icon = "short_range_scanner",
    unlock_flags = "UnlocksShortRangeScanner|ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 1,
      },
    },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_short_range_scanner_crystals"] = {
    identifier = "_base_short_range_scanner_crystals",
    title = "Crystal-Scanning",
    description = [[Tunes the short range scanner so that it can track Xeno-Crystals.

Note: Scan range might not be high enough to detect Xeno-Crystals from the surface.]],
    category_id = "_base_tools",
    icon = "short_range_scanner",
    unlock_flags = "ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 1,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_short_range_scanner",
      },
    },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_short_range_scanner_power_core_ii"] = {
    identifier = "_base_short_range_scanner_power_core_ii",
    title = "Xeno Power Core Scanning",
    description = [[Tunes the short range scanner so that it can track intact Xeno Power Cores.

Note: Scan range might not be high enough to detect those buried pieces from the surface.]],
    category_id = "_base_tools",
    icon = "short_range_scanner",
    unlock_flags = "ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    sort_order = 50,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_ii",
        amount = 500,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_short_range_scanner",
      },
    },
    research_dependencies = { "_base_mining_force_ii" },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_short_range_scanner_scrap_ii"] = {
    identifier = "_base_short_range_scanner_scrap_ii",
    title = "Large Xeno-Scrap Scanning",
    description = [[Tunes the short range scanner so that it can track larger Xeno-Scrap pieces, which may contain damaged Xeno Power Cores.

Note: Large Xeno-Scrap can be tracked from the surface, but you'll have to explore a bit until you get close enough. Open your scanning frame (default key: J) to customize which objects the Short Range Scanner should track.]],
    category_id = "_base_tools",
    icon = "short_range_scanner",
    unlock_flags = "ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    sort_order = 50,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 50,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_short_range_scanner",
      },
    },
    research_dependencies = { "_base_mining_force_i" },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_short_range_scanner_surface_caves"] = {
    identifier = "_base_short_range_scanner_surface_caves",
    title = "Cave-Scanning",
    description = [[Tunes the short range scanner so that it can track Xeno-Scrap pieces buried in underground caves where we will be able to find a lot more scrap in a more condensed area.

Open your scanning frame (default key: J) to customize which objects the Short Range Scanner should track.]],
    category_id = "_base_tools",
    icon = "short_range_scanner",
    unlock_flags = "ShortRangeScannerBotUnlock",
    seconds_to_unlock = 5,
    sort_order = 50,
    requirements = {
      {
        itemTemplateIdentifier = "_base_alien_scrap_i",
        amount = 20,
      },
    },
    unlock_dependencies = {
      {
        explorationUnlockTemplateIdentifier = "_base_short_range_scanner",
      },
    },
    crafting_recipe_unlocks = { "_base_drill_ship_i" },
  },
  ["_base_water_tool"] = {
    identifier = "_base_water_tool",
    title = "Irrigation Tool",
    description = "The Irrigation Tool shoots a stream of water which allows you to regrow grass on dirt terrain.",
    category_id = "_base_tools",
    icon = "water_tool",
    unlock_flags = "UnlockCraftingRecipe",
    seconds_to_unlock = 5,
    requirements = {
      {
        itemTemplateIdentifier = "_base_crystal_i",
        amount = 10,
      },
    },
    research_dependencies = { "_base_piping" },
    crafting_recipe_unlocks = { "_base_water_tool" },
  },
}
