-- Module:Data/Industries
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 8 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_administrative"] = {
    identifier = "_base_administrative",
    name = "Appliances",
  },
  ["_base_agricultural"] = {
    identifier = "_base_agricultural",
    name = "Agricultural",
  },
  ["_base_ecological"] = {
    identifier = "_base_ecological",
    name = "Ecological",
  },
  ["_base_logistic"] = {
    identifier = "_base_logistic",
    name = "Logistics",
  },
  ["_base_metallurgy"] = {
    identifier = "_base_metallurgy",
    name = "Metallurgy",
  },
  ["_base_military"] = {
    identifier = "_base_military",
    name = "Military",
  },
  ["_base_mining"] = {
    identifier = "_base_mining",
    name = "Mining",
  },
  ["_base_scientific"] = {
    identifier = "_base_scientific",
    name = "Scientific",
  },
}
