-- Module:Data/ItemCategories
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 5 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_components"] = {
    identifier = "_base_components",
    name = "Components",
    icon = "components",
    sort_order = 20,
    station_capacity_per_level = 1000,
  },
  ["_base_construction_material"] = {
    identifier = "_base_construction_material",
    name = "Construction Material",
    icon = "ic_construction_material",
    sort_order = 10,
    station_capacity_per_level = 2500,
  },
  ["_base_raw_materials"] = {
    identifier = "_base_raw_materials",
    name = "Raw Materials",
    icon = "ic_raw_materials",
    sort_order = 40,
    station_capacity_per_level = 1000,
  },
  ["_base_resources"] = {
    identifier = "_base_resources",
    name = "Resources",
    icon = "ic_resources",
    sort_order = 50,
    station_capacity_per_level = 2000,
  },
  ["_base_sales_items"] = {
    identifier = "_base_sales_items",
    name = "Products",
    icon = "ic_sales_items",
    station_capacity_per_level = 200,
  },
}
