-- Module:Data/OreVeins
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 5 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_ore_vein_template_ignium"] = {
    identifier = "_base_ore_vein_template_ignium",
    outer_layer_block = "_base_oreveinexterior",
    mineable_block = "_base_oreveinmineable_ignium",
    core_block = "_base_oreveincore_ignium",
    spawn_chance = 33,
    mining_fluid_id = "_base_fracking_liquid_i",
    mining_fluid_rate = 150,
  },
  ["_base_ore_vein_template_mineral_rock"] = {
    identifier = "_base_ore_vein_template_mineral_rock",
    outer_layer_block = "_base_oreveinexterior",
    mineable_block = "_base_oreveinmineable_mineral_rock",
    core_block = "_base_oreveincore_mineral_rock",
    spawn_chance = 53,
    mining_fluid_id = "_base_fracking_liquid_i",
    mining_fluid_rate = 150,
  },
  ["_base_ore_vein_template_technum"] = {
    identifier = "_base_ore_vein_template_technum",
    outer_layer_block = "_base_oreveinexterior",
    mineable_block = "_base_oreveinmineable_te",
    core_block = "_base_oreveincore_technum",
    spawn_chance = 33,
    mining_fluid_id = "_base_fracking_liquid_i",
    mining_fluid_rate = 150,
  },
  ["_base_ore_vein_template_telluxite"] = {
    identifier = "_base_ore_vein_template_telluxite",
    outer_layer_block = "_base_oreveinexterior",
    mineable_block = "_base_oreveinmineable_telluxite",
    core_block = "_base_oreveincore_telluxite",
    spawn_chance = 40,
    mining_fluid_id = "_base_fracking_liquid_i",
    mining_fluid_rate = 150,
  },
  ["_base_ore_vein_template_xenoferrite"] = {
    identifier = "_base_ore_vein_template_xenoferrite",
    outer_layer_block = "_base_oreveinexterior",
    mineable_block = "_base_oreveinmineable_xf",
    core_block = "_base_oreveincore",
    spawn_chance = 33,
    mining_fluid_id = "_base_fracking_liquid_i",
    mining_fluid_rate = 150,
  },
}
