-- Module:Data/Quests
-- Auto-generated by foundry_parser on 2026-05-30 12:42 UTC
-- 26 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_mq_ass2conv2"] = {
    identifier = "_base_mq_ass2conv2",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_conveyor_ii",
        additionalData01 = 1,
      },
      {
        type = "ResearchComplete",
        identifier01 = "_base_assembler_ii",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_assembly_lines"] = {
    identifier = "_base_mq_assembly_lines",
    title = "Assembly Lines",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_assembly_lines",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_construction_industry" },
    research_dependencies = { "_base_science_pack_iv" },
  },
  ["_base_mq_assembly_lines_build"] = {
    identifier = "_base_mq_assembly_lines_build",
    title = "Build Assembly Line",
    conditions = {
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 7,
      },
    },
    quest_dependencies = { "_base_mq_assembly_lines" },
  },
  ["_base_mq_blast_furnace"] = {
    identifier = "_base_mq_blast_furnace",
    title = "Going Big",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_blast_furnace",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_assembly_lines_build" },
    research_dependencies = { "_base_science_pack_iv" },
  },
  ["_base_mq_burner_generator"] = {
    identifier = "_base_mq_burner_generator",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_ore_scanner_ignium",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_cargo_ships"] = {
    identifier = "_base_mq_cargo_ships",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_long_distance_transport",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_construction_bay"] = {
    identifier = "_base_mq_construction_bay",
    title = "Construction Drone Bay",
    conditions = {
      {
        type = "SkyPlatformUpgrade",
        identifier01 = "_base_construction_drone_bay_i",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_station_antenna" },
  },
  ["_base_mq_construction_industry"] = {
    identifier = "_base_mq_construction_industry",
    title = "Construction Industry",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_construction_drone_ports",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_energy_cells" },
  },
  ["_base_mq_elevator"] = {
    identifier = "_base_mq_elevator",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_elevator_i",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_energy_cells"] = {
    identifier = "_base_mq_energy_cells",
    title = "Energy Cells",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_energy_cell",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_olumite" },
    research_dependencies = { "_base_chemical_processing" },
  },
  ["_base_mq_greenhouse"] = {
    identifier = "_base_mq_greenhouse",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_greenhouse_i",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_hvg_power"] = {
    identifier = "_base_mq_hvg_power",
    title = "High-Voltage Power",
    conditions = {
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_boiler_i",
        additionalData01 = 2,
      },
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_turbine_i",
        additionalData01 = 2,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_station_antenna" },
    research_dependencies = { "_base_basic_steelmaking" },
  },
  ["_base_mq_ignium_power"] = {
    identifier = "_base_mq_ignium_power",
    title = "Automated Power",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_burner_generator_lvg",
        additionalData01 = 1,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 0,
      },
    },
    quest_dependencies = { "_base_mq_stabilize_station" },
  },
  ["_base_mq_market"] = {
    identifier = "_base_mq_market",
    title = "Galactic Market",
    conditions = {
      {
        type = "ViewInfoDB",
        identifier01 = "_base_market",
        additionalData01 = 0,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 2,
      },
    },
    quest_dependencies = { "_base_mq_station_antenna" },
  },
  ["_base_mq_mining_efficiency"] = {
    identifier = "_base_mq_mining_efficiency",
    title = "Increasing Efficiency",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_mining_efficiency",
        additionalData01 = 5,
      },
    },
    quest_dependencies = { "_base_mq_blast_furnace" },
  },
  ["_base_mq_olumite"] = {
    identifier = "_base_mq_olumite",
    title = "Olumite",
    conditions = {
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_pumpjack_i",
        additionalData01 = 4,
      },
    },
    quest_dependencies = { "_base_mq_hvg_power" },
    research_dependencies = { "_base_science_pack_iii" },
  },
  ["_base_mq_omni_analyzer"] = {
    identifier = "_base_mq_omni_analyzer",
    is_milestone = true,
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_exploration_analyzer",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_stabilize_station"] = {
    identifier = "_base_mq_stabilize_station",
    title = "Stabilize Space Station",
    conditions = {
      {
        type = "SkyPlatformUpgrade",
        identifier01 = "_base_hull_01",
        additionalData01 = 1,
      },
    },
  },
  ["_base_mq_station_antenna"] = {
    identifier = "_base_mq_station_antenna",
    title = "Space Station Antenna",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_science_pack_ii",
        additionalData01 = 1,
      },
      {
        type = "ResearchComplete",
        identifier01 = "_base_space_station_antenna",
        additionalData01 = 1,
      },
      {
        type = "SkyPlatformUpgrade",
        identifier01 = "_base_antenna_01",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_ignium_power" },
  },
  ["_base_sector_selling"] = {
    identifier = "_base_sector_selling",
    title = "Planetary Sales",
    conditions = {
      {
        type = "SkyPlatformUpgrade",
        identifier01 = "_base_antenna_02",
        additionalData01 = 1,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 3,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 4,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 5,
      },
    },
    quest_dependencies = { "_base_mq_market" },
  },
  ["_base_sq_jetack"] = {
    identifier = "_base_sq_jetack",
    title = "Jetpack",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_jetpack",
        additionalData01 = 1,
      },
    },
    quest_dependencies = { "_base_mq_olumite" },
  },
  ["_base_sq_lava_caves"] = {
    identifier = "_base_sq_lava_caves",
    title = "Lava Caves",
    conditions = {
      {
        type = "ResearchComplete",
        identifier01 = "_base_firmarlite_smelting_basic",
        additionalData01 = 1,
      },
      {
        type = "ViewInfoDB",
        identifier01 = "_base_lava_caves",
        additionalData01 = 0,
      },
      {
        type = "ResearchComplete",
        identifier01 = "_base_elevator_i",
        additionalData01 = 1,
      },
      {
        type = "ResearchComplete",
        identifier01 = "_base_freight_elevator_i",
        additionalData01 = 1,
      },
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_smelter_lava_i",
        additionalData01 = 2,
      },
      {
        type = "ItemsMade",
        identifier01 = "_base_firmarlite_sheet",
        additionalData01 = 50,
      },
    },
    research_dependencies = { "_base_ore_refinement_i" },
  },
  ["_base_sq_lights"] = {
    identifier = "_base_sq_lights",
    title = "Lights",
    conditions = {
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_lightpole_i",
        additionalData01 = 5,
      },
    },
    research_dependencies = { "_base_lights_i" },
  },
  ["_base_sq_radio_tower"] = {
    identifier = "_base_sq_radio_tower",
    title = "Radio Tower",
    conditions = {
      {
        type = "ViewInfoDB",
        identifier01 = "_base_construction_industry",
        additionalData01 = 0,
      },
      {
        type = "ResearchComplete",
        identifier01 = "_base_station_radio_tower",
        additionalData01 = 1,
      },
      {
        type = "CustomCondition",
        identifier01 = "",
        additionalData01 = 6,
      },
    },
    quest_dependencies = { "_base_mq_construction_industry" },
  },
  ["_base_sq_smelters"] = {
    identifier = "_base_sq_smelters",
    title = "Expand Smelters",
    conditions = {
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_smelter_small_i",
        additionalData01 = 16,
      },
    },
    quest_dependencies = { "_base_mq_ignium_power" },
    research_dependencies = { "_base_infrastructure_i" },
  },
  ["_base_sq_underground_mining"] = {
    identifier = "_base_sq_underground_mining",
    title = "Underground Mining",
    conditions = {
      {
        type = "BuildingsBuilt",
        identifier01 = "_base_ore_vein_miner_i",
        additionalData01 = 2,
      },
    },
    research_dependencies = { "_base_underground_mining_i" },
  },
}
