-- Module:Data/RecipeCategories
-- Auto-generated by foundry_parser on 2026-05-31 10:26 UTC
-- 8 entries
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_buildings"] = {
    identifier = "_base_buildings",
    name = "Structures",
    icon = "structures",
    default_row_group = "_base_buildings_general",
  },
  ["_base_components"] = {
    identifier = "_base_components",
    name = "Components",
    icon = "components",
    default_row_group = "_base_components_general",
    sort_order = 10,
  },
  ["_base_decor"] = {
    identifier = "_base_decor",
    name = "Decor",
    icon = "category_decor",
    default_row_group = "_base_decor_general",
    sort_order = 30,
  },
  ["_base_general"] = {
    identifier = "_base_general",
    name = "General",
    default_row_group = "_base_general_general",
    sort_order = -5,
  },
  ["_base_handhelds"] = {
    identifier = "_base_handhelds",
    name = "Handhelds",
    icon = "handhelds",
    default_row_group = "_base_handhelds_general",
    sort_order = 40,
  },
  ["_base_metallurgy"] = {
    identifier = "_base_metallurgy",
    name = "Metallurgy",
    icon = "metallurgy",
    default_row_group = "_base_general_metallurgy",
    sort_order = 20,
  },
  ["_base_robots"] = {
    identifier = "_base_robots",
    name = "Robots",
    icon = "category_robots",
    default_row_group = "_base_general_robots",
    sort_order = 15,
  },
  ["_base_super_buildings"] = {
    identifier = "_base_super_buildings",
    name = "Buildings",
    icon = "hot_air_stove_base",
    default_row_group = "_base_general_super_buildings",
    sort_order = 60,
  },
}
