-- Module:Data/UpgradePaths
-- Auto-generated by foundry_parser on 2026-05-31 10:26 UTC
-- building_id -> flat table of upgrade chain building names
-- Access: entry.n = count, entry.n1 = first name, etc.
-- DO NOT EDIT - regenerate from game data instead

return {
  ["_base_assembler_i"] = { n = 3, n1 = "Assembler I", n2 = "Assembler II", n3 = "Assembler III" },
  ["_base_assembler_ii"] = { n = 3, n1 = "Assembler I", n2 = "Assembler II", n3 = "Assembler III" },
  ["_base_assembler_iii"] = { n = 3, n1 = "Assembler I", n2 = "Assembler II", n3 = "Assembler III" },
  ["_base_conveyor_balancer_i"] = { n = 4, n1 = "Conveyor Balancer I", n2 = "Conveyor Balancer II", n3 = "Conveyor Balancer III", n4 = "Conveyor Balancer IV" },
  ["_base_conveyor_balancer_ii"] = { n = 4, n1 = "Conveyor Balancer I", n2 = "Conveyor Balancer II", n3 = "Conveyor Balancer III", n4 = "Conveyor Balancer IV" },
  ["_base_conveyor_balancer_iii"] = { n = 4, n1 = "Conveyor Balancer I", n2 = "Conveyor Balancer II", n3 = "Conveyor Balancer III", n4 = "Conveyor Balancer IV" },
  ["_base_conveyor_balancer_iv"] = { n = 4, n1 = "Conveyor Balancer I", n2 = "Conveyor Balancer II", n3 = "Conveyor Balancer III", n4 = "Conveyor Balancer IV" },
  ["_base_conveyor_i"] = { n = 4, n1 = "Conveyor I", n2 = "Conveyor II", n3 = "Conveyor III", n4 = "Conveyor IV" },
  ["_base_conveyor_ii"] = { n = 4, n1 = "Conveyor I", n2 = "Conveyor II", n3 = "Conveyor III", n4 = "Conveyor IV" },
  ["_base_conveyor_iii"] = { n = 4, n1 = "Conveyor I", n2 = "Conveyor II", n3 = "Conveyor III", n4 = "Conveyor IV" },
  ["_base_conveyor_iv"] = { n = 4, n1 = "Conveyor I", n2 = "Conveyor II", n3 = "Conveyor III", n4 = "Conveyor IV" },
  ["_base_conveyor_slope_i"] = { n = 4, n1 = "Conveyor Slope I", n2 = "Conveyor Slope II", n3 = "Conveyor Slope III", n4 = "Conveyor Slope IV" },
  ["_base_conveyor_slope_ii"] = { n = 4, n1 = "Conveyor Slope I", n2 = "Conveyor Slope II", n3 = "Conveyor Slope III", n4 = "Conveyor Slope IV" },
  ["_base_conveyor_slope_iii"] = { n = 4, n1 = "Conveyor Slope I", n2 = "Conveyor Slope II", n3 = "Conveyor Slope III", n4 = "Conveyor Slope IV" },
  ["_base_conveyor_slope_iv"] = { n = 4, n1 = "Conveyor Slope I", n2 = "Conveyor Slope II", n3 = "Conveyor Slope III", n4 = "Conveyor Slope IV" },
  ["_base_crusher_i"] = { n = 2, n1 = "Crusher I", n2 = "Crusher II" },
  ["_base_crusher_ii"] = { n = 2, n1 = "Crusher I", n2 = "Crusher II" },
  ["_base_drone_miner_i"] = { n = 2, n1 = "Drone Miner I", n2 = "Drone Miner II" },
  ["_base_drone_miner_ii"] = { n = 2, n1 = "Drone Miner I", n2 = "Drone Miner II" },
  ["_base_escalator_straight"] = { n = 3, n1 = "Escalator I", n2 = "Escalator II", n3 = "Escalator III" },
  ["_base_escalator_straight_ii"] = { n = 3, n1 = "Escalator I", n2 = "Escalator II", n3 = "Escalator III" },
  ["_base_escalator_straight_iii"] = { n = 3, n1 = "Escalator I", n2 = "Escalator II", n3 = "Escalator III" },
  ["_base_freight_elevator_i_bottom"] = { n = 4, n1 = "Freight Elevator I", n2 = "Freight Elevator II", n3 = "Freight Elevator III", n4 = "Freight Elevator IV" },
  ["_base_freight_elevator_ii_bottom"] = { n = 4, n1 = "Freight Elevator I", n2 = "Freight Elevator II", n3 = "Freight Elevator III", n4 = "Freight Elevator IV" },
  ["_base_freight_elevator_iii_bottom"] = { n = 4, n1 = "Freight Elevator I", n2 = "Freight Elevator II", n3 = "Freight Elevator III", n4 = "Freight Elevator IV" },
  ["_base_freight_elevator_iv_bottom"] = { n = 4, n1 = "Freight Elevator I", n2 = "Freight Elevator II", n3 = "Freight Elevator III", n4 = "Freight Elevator IV" },
  ["_base_smelter_lava_i"] = { n = 2, n1 = "Lava-Smelter I", n2 = "Lava-Smelter II" },
  ["_base_smelter_lava_ii"] = { n = 2, n1 = "Lava-Smelter I", n2 = "Lava-Smelter II" },
}
