"""
MediaWiki Upload Tool

Uploads generated wiki pages to a MediaWiki site via the API.
Supports dry-run mode, incremental updates, and diff preview.

Usage:
    from foundry_parser.wiki_upload import WikiUploader

    uploader = WikiUploader(
        site_url="https://wiki.foundry-game.com",
        username="BotAccount",
        password="bot_password",
    )
    uploader.upload_pages(
        pages_dir=Path("wiki_pages/"),
        dry_run=True,
    )
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests


@dataclass
class UploadResult:
    """Result of uploading a single page."""
    title: str
    status: str  # "created", "updated", "unchanged", "skipped", "error"
    message: str = ""
    old_size: int = 0
    new_size: int = 0


@dataclass
class WikiUploader:
    """Handles authentication and page uploads to a MediaWiki site."""

    site_url: str
    username: str = ""
    password: str = ""
    api_url: str = field(init=False)
    session: requests.Session = field(default_factory=requests.Session, repr=False)
    rate_limit: float = 1.0  # seconds between edits
    edit_summary: str = "Auto-generated by Foundry Wiki Tools"
    bot_flag: bool = True
    csrf_token: str = ""

    def __post_init__(self) -> None:
        self.api_url = self.site_url.rstrip("/") + "/api.php"
        self.session.headers.update({
            "User-Agent": "FoundryWikiTools/0.1 (wiki upload; foundry-wiki-tools)",
        })

    # ------------------------------------------------------------------
    # Authentication
    # ------------------------------------------------------------------

    def login(self) -> bool:
        """Log in to the wiki using bot credentials."""
        # Step 1: Get login token
        resp = self.session.get(self.api_url, params={
            "action": "query",
            "meta": "tokens",
            "type": "login",
            "format": "json",
        })
        data = resp.json()
        login_token = data["query"]["tokens"]["logintoken"]

        # Step 2: Log in
        resp = self.session.post(self.api_url, data={
            "action": "login",
            "lgname": self.username,
            "lgpassword": self.password,
            "lgtoken": login_token,
            "format": "json",
        })
        data = resp.json()
        if data.get("login", {}).get("result") != "Success":
            raise ConnectionError(
                f"Login failed: {data.get('login', {}).get('reason', 'unknown')}"
            )

        # Step 3: Get CSRF token for editing
        self.refresh_csrf_token()

        return True

    def refresh_csrf_token(self) -> None:
        """Re-fetch the CSRF token from the API (no re-login required).

        Called automatically when a ``badtoken`` error is encountered mid-batch.
        """
        resp = self.session.get(self.api_url, params={
            "action": "query",
            "meta": "tokens",
            "format": "json",
        })
        data = resp.json()
        self.csrf_token = data["query"]["tokens"]["csrftoken"]

    # ------------------------------------------------------------------
    # Page operations
    # ------------------------------------------------------------------

    def get_page_content(self, title: str) -> str | None:
        """Get the current content of a page, or None if it doesn't exist."""
        resp = self.session.get(self.api_url, params={
            "action": "query",
            "titles": title,
            "prop": "revisions",
            "rvprop": "content",
            "rvslots": "main",
            "format": "json",
        })
        data = resp.json()
        pages = data.get("query", {}).get("pages", {})
        for page_id, page_data in pages.items():
            if "missing" in page_data:
                return None
            revisions = page_data.get("revisions", [])
            if revisions:
                return revisions[0].get("slots", {}).get("main", {}).get("*", "")
        return None

    def edit_page(
        self, title: str, content: str, summary: str = "",
        content_model: str = "",
    ) -> dict[str, Any]:
        """Edit (create or update) a page.

        Args:
            content_model: Optional content model override, e.g. "sanitized-css"
                           for TemplateStyles CSS pages.
        """
        if not self.csrf_token:
            raise RuntimeError("Not logged in. Call login() first.")

        time.sleep(self.rate_limit)

        params = {
            "action": "edit",
            "title": title,
            "text": content,
            "summary": summary or self.edit_summary,
            "token": self.csrf_token,
            "format": "json",
        }
        if content_model:
            params["contentmodel"] = content_model
        if self.bot_flag:
            params["bot"] = "1"

        resp = self.session.post(self.api_url, data=params)
        result = resp.json()

        # If the CSRF token expired mid-session, refresh it and retry once.
        if result.get("error", {}).get("code") == "badtoken":
            self.refresh_csrf_token()
            params["token"] = self.csrf_token
            resp = self.session.post(self.api_url, data=params)
            result = resp.json()

        return result

    def upload_file(
        self,
        file_path: Path,
        dest_filename: str = "",
        summary: str = "",
        overwrite: bool = True,
        text: str = "",
    ) -> dict[str, Any]:
        """Upload a binary file (image, etc.) to the wiki.

        Uses the MediaWiki ``action=upload`` multipart API.

        Args:
            file_path:     Path to the local file to upload.
            dest_filename: Wiki filename (without ``File:`` prefix).  Defaults
                           to the local filename.
            summary:       Edit comment shown in the file's upload log.
            overwrite:     If True, passes ``ignorewarnings=1`` so that an
                           existing file with the same name is overwritten.
            text:          Wikitext for the file description page (sets
                           author, licence, category, etc.).  If omitted the
                           wiki's default upload text is used.
        """
        if not self.csrf_token:
            raise RuntimeError("Not logged in. Call login() first.")

        time.sleep(self.rate_limit)

        filename = dest_filename or file_path.name

        params: dict[str, Any] = {
            "action": "upload",
            "filename": filename,
            "comment": summary or self.edit_summary,
            "token": self.csrf_token,
            "format": "json",
        }
        if text:
            params["text"] = text
        if overwrite:
            params["ignorewarnings"] = "1"

        with file_path.open("rb") as fh:
            resp = self.session.post(
                self.api_url,
                data=params,
                files={"file": (filename, fh, "application/octet-stream")},
            )

        result = resp.json()

        # Refresh CSRF token and retry once on badtoken error
        if result.get("error", {}).get("code") == "badtoken":
            self.refresh_csrf_token()
            params["token"] = self.csrf_token
            with file_path.open("rb") as fh:
                resp = self.session.post(
                    self.api_url,
                    data=params,
                    files={"file": (filename, fh, "application/octet-stream")},
                )
            result = resp.json()

        return result

    # ------------------------------------------------------------------
    # Batch upload
    # ------------------------------------------------------------------

    def upload_pages(
        self,
        pages_dir: Path,
        dry_run: bool = True,
        incremental: bool = True,
        namespace_map: dict[str, str] | None = None,
        verbose: bool = True,
    ) -> list[UploadResult]:
        """
        Upload all pages from a directory to the wiki.

        Args:
            pages_dir: Directory containing .wikitext files (can have subdirs).
            dry_run: If True, don't actually upload — just report what would change.
            incremental: If True, skip pages whose content matches the wiki.
            namespace_map: Maps subdirectory names to wiki namespaces.
                          Default: {"navboxes": "Template:", "lua_modules": "Module:Data/"}
            verbose: Print progress.

        Returns:
            List of UploadResult for each page processed.
        """
        if namespace_map is None:
            namespace_map = {
                "navboxes": "",  # navbox files already have Template_ prefix
            }

        def log(msg: str) -> None:
            if verbose:
                print(msg)

        results: list[UploadResult] = []

        # Collect pages
        pages: list[tuple[str, Path]] = []
        for wikitext_file in pages_dir.rglob("*.wikitext"):
            title = self._file_to_title(wikitext_file, pages_dir, namespace_map)
            pages.append((title, wikitext_file))

        log(f"Found {len(pages)} pages to upload")
        if dry_run:
            log("DRY RUN — no changes will be made\n")

        for i, (title, filepath) in enumerate(sorted(pages), 1):
            new_content = filepath.read_text(encoding="utf-8").rstrip()

            if incremental and not dry_run:
                # Check current content
                current = self.get_page_content(title)
                if current is not None and current.rstrip() == new_content:
                    result = UploadResult(
                        title=title,
                        status="unchanged",
                        new_size=len(new_content),
                        old_size=len(current),
                    )
                    results.append(result)
                    continue

            if dry_run:
                # In dry-run, just report
                status = "would_create"  # We don't check remote in dry-run
                result = UploadResult(
                    title=title,
                    status=status,
                    new_size=len(new_content),
                )
                results.append(result)
                log(f"  [{i}/{len(pages)}] {status}: {title} ({len(new_content)} bytes)")
            else:
                try:
                    response = self.edit_page(title, new_content)
                    edit_data = response.get("edit", {})
                    if edit_data.get("result") == "Success":
                        status = "created" if edit_data.get("new") else "updated"
                        result = UploadResult(
                            title=title,
                            status=status,
                            new_size=len(new_content),
                        )
                        log(f"  [{i}/{len(pages)}] {status}: {title}")
                    else:
                        result = UploadResult(
                            title=title,
                            status="error",
                            message=str(response.get("error", edit_data)),
                        )
                        log(f"  [{i}/{len(pages)}] ERROR: {title} — {result.message}")
                except Exception as e:
                    result = UploadResult(
                        title=title,
                        status="error",
                        message=str(e),
                    )
                    log(f"  [{i}/{len(pages)}] ERROR: {title} — {e}")

                results.append(result)

        # Summary
        statuses = {}
        for r in results:
            statuses[r.status] = statuses.get(r.status, 0) + 1
        log(f"\nUpload summary:")
        for status, count in sorted(statuses.items()):
            log(f"  {status}: {count}")

        return results

    def _file_to_title(
        self, filepath: Path, base_dir: Path, namespace_map: dict[str, str]
    ) -> str:
        """Convert a file path to a wiki page title."""
        relative = filepath.relative_to(base_dir)
        parts = list(relative.parts)

        # Check if first directory maps to a namespace
        title = filepath.stem  # filename without .wikitext
        if len(parts) > 1:
            subdir = parts[0]
            if subdir in namespace_map:
                prefix = namespace_map[subdir]
                title = prefix + title
            # For template files with Template_ prefix, convert to namespace
            if title.startswith("Template_"):
                title = "Template:" + title[9:].replace("_", " ")

        return title

    # ------------------------------------------------------------------
    # Lua module upload
    # ------------------------------------------------------------------

    def upload_lua_modules(
        self,
        lua_dir: Path,
        dry_run: bool = True,
        verbose: bool = True,
    ) -> list[UploadResult]:
        """Upload Lua data modules to Module:Data/* namespace."""
        results: list[UploadResult] = []

      